import { Router } from "express";

import { AuthenticationController } from "../controllers";

const router = Router();

/**
 * @openapi
 * /authentication/nonce:
 *   post:
 *     description: Generates a nonce for a given wallet
 *     tags: [Authentication]
 *     requestBody:
 *       description: a JSON object containing wallet public key
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/NonceRequest'
 *           example:
 *             wallet: wallet's public key
 *     responses:
 *       200:
 *         description: Nonce (TTL 60s)
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/NonceResponse'
 *       4XX:
 *         description: Nonce Creation Failed
 */
router.post("/nonce"
  , AuthenticationController.generateNonce
);

/**
 * @openapi
 * /authentication/login:
 *   post:
 *     description: Creates access token and refresh token for wallet
 *     tags: [Authentication]
 *     requestBody:
 *       description: a JSON object containing wallet public key & signed message
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/AuthTokenCreateRequest'
 *           example:
 *             wallet: wallet's public key
 *             nonce: valid nonce for public key & time generated by server (plaintext of message contents)
 *             message: nonce encrypted by wallets private key
 *     responses:
 *       200:
 *         description: Access Token
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/AuthTokenCreateResponse'
 *       401:
 *         description: Token Pair Creation Failed
 */
router.post("/login"
  , AuthenticationController.verifySignature
  , AuthenticationController.createAccessToken
);

export default router;
