AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKey: 434486c28a50b9acd7830bbc129ca5eb
      nodeLayerVersion: 78
      extensionLayerVersion: 22
      site: "datadoghq.com"
      env: !Ref Env # Optional
      service: collection-metadata-attribute-processor
Description: >
  collection-metadata-attribute-processor

  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 240
    Runtime: nodejs14.x

Parameters:
  Env: 
    Type: String
    AllowedValues:
      - testing
      - prod
    Description: Environment in which the app will be deployed

Mappings:
  EnvMapping:
    testing:
      DynamoDbEndpoint: ''
      DynamoDBARN: 'arn:aws:dynamodb:entitydb-arn/stream/2022-06-06T22:53:11.390'
      EntityTableName: playdust-parrotfish-entitydb
      FunctionName: collection-metadata-attribute-processor-testing
      NFTmintSQSName: 'NFTMetadata-to-OS'
      CollectionIDSQSName: 'DuplicateCollectionIdtoOSQueue'
    prod:
      DynamoDbEndpoint: '' 
      DynamoDBARN: 'arn:aws:dynamodb:us-east-1:513523160844:table/playdust-parrotfish-prod-entitydb/stream/2022-06-07T18:55:10.458'
      EntityTableName: playdust-parrotfish-prod-entitydb
      FunctionName: collection-metadata-attribute-processor-prod
      NFTmintSQSName: 'NFTMetadata-to-OS'
      CollectionIDSQSName: 'DuplicateCollectionIdtoOSQueue'

Resources:
  CollectionIdSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 241
      QueueName: CollectionIdSQSQueue
  CollectionMetadataAttributeProcessor:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties: 
      FunctionName: !FindInMap [ EnvMapping, !Ref Env, FunctionName ]
      CodeUri: ./build
      Handler: lambdaEntrypoint.handler
      MemorySize: 1024
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: !FindInMap [ EnvMapping, !Ref Env, DynamoDbEndpoint ]
          ENTITY_TABLE_NAME: !FindInMap [ EnvMapping, !Ref Env, EntityTableName ]
          NFT_QUEUE_NAME: !FindInMap [ EnvMapping, !Ref Env, NFTmintSQSName ]
          COLLECTION_OS_QUEUE_NAME: !FindInMap [ EnvMapping, !Ref Env, CollectionIDSQSName ]
          COLLECTION_QUEUE_URL: !Ref CollectionIdSQSQueue
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
        - SQSPollerPolicy:
            QueueName: !GetAtt CollectionIdSQSQueue.QueueName
        - SQSSendMessagePolicy:
            QueueName: !FindInMap [ EnvMapping, !Ref Env, NFTmintSQSName ]
            QueueName: !FindInMap [ EnvMapping, !Ref Env, CollectionIDSQSName ]
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt CollectionIdSQSQueue.Arn
            BatchSize: 1

