AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKey: 434486c28a50b9acd7830bbc129ca5eb
      nodeLayerVersion: 78
      extensionLayerVersion: 22
      site: "datadoghq.com"
      env: !Ref Env # Optional
      service: entity-trigger
Description: >
  entity-trigger

  Entity trigger
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Runtime: nodejs14.x

Parameters:
  Env: 
    Type: String
    AllowedValues:
      - testing
      - prod
    Description: Environment in which the app will be deployed

Mappings:
  EnvMapping:
    testing:
      DynamoDbEndpoint: ''
      DynamoDBARN: 'arn:aws:dynamodb:entitydb-arn/stream/2022-04-28T17:51:21.735' 
      EntityTableName: playdust-parrotfish-entitydb
      FunctionName: entity-trigger-testing
    prod:
      DynamoDbEndpoint: '' 
      DynamoDBARN: 'arn:aws:dynamodb:us-east-1:513523160844:table/playdust-parrotfish-entitydb/stream/2022-06-06T17:49:47.240'
      EntityTableName: playdust-parrotfish-entitydb
      FunctionName: entity-trigger-prod

Resources:
  EntityTrigger:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties: 
      CodeUri: ./build
      FunctionName: !FindInMap [ EnvMapping, !Ref Env, FunctionName ]
      Handler: lambdaEntrypoint.lambdaHandler
      MemorySize: 256
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENTITY_TABLE_NAME: !FindInMap [ EnvMapping, !Ref Env, EntityTableName ]
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !FindInMap [ EnvMapping, !Ref Env, DynamoDBARN ]
            BatchSize: 1
            StartingPosition: TRIM_HORIZON
            FilterCriteria:
              Filters:
                - Pattern: "{
                    \"dynamodb\": {
                      \"NewImage\": {
                        \"type\": {
                          \"S\": [{\"anything-but\":[\"trigger\"]}]
                        }
                      }
                    }
                  }"
